Remove inline direective in private functions
Inline directives in the private functions of the RingBuffer class template have been removed.
When compilation by g++ 11.3 with the release option, RingBuffer instantiation fails with the following errors.

```
RingBuffer.h:846:17: error: inlining failed in call to ‘void RTC::RingBuffer<DataType>::initLength(const coil::Properties&) [with DataType = RTC::ByteData]’: --param max-inline-insns-single limit reached [-Werror=inline]
  846 |     inline void initLength(const coil::Properties& prop)
```